### ISSUE TITLE
NOCS-REAL275的 GT位姿准确吗?

### ISSUE THREAD

**Issue by Liuchongpei** [densechen/CASS#3]
你好，我运行了NOCS的检测程序会生成许多GT位姿可视化的图片（名为“*bbox_gt.png”）。从这些图片中明显可以看出一些物体的GT位姿不对，请问你的有没有遇到这样的情况？
![2345截图20200813153632](https://user-images.githubusercontent.com/34116796/90133439-0fef4180-dda2-11ea-80ed-2a8e33881964.jpg)
![2345截图20200813153709](https://user-images.githubusercontent.com/34116796/90133445-11b90500-dda2-11ea-844c-6660f82e00ea.jpg)

**Comment by densechen** [comment]
是这样。NOCS的真实数据集无论是测试还是训练，其标注的位姿都存在一些误差。
这个问题大家普遍承认。如果你想要得到一个更准确的GT的话， 你可以自己手动调整一下， 或者直接下载6PACK（https://github.com/j96w/6-PACK）代码提供的他们调整过后的位姿。

**Comment by Liuchongpei** [comment]
好的，谢谢，不过6PACK似乎只调整了real_train的GT位姿，未调整real_test的GT位姿

**Comment by densechen** [comment]
额，我印象中是只调整了test的位姿，没有调整train的位姿才对。不过这个位姿的不准确，大家觉得是可以容忍的。所以，也一直都将就的用着

**Comment by Liuchongpei** [comment]
6PACK应该只调整了train的GT位姿
![2345截图20200815104800](https://user-images.githubusercontent.com/34116796/90303957-75981680-dee5-11ea-83e9-9100ae4ab454.jpg)
从上面的图片中粗略估计一些物体的GT位姿的角度误差超过10°，而评价标准是5°，10°等。如果改进方法以提高在评价标准上分数，似乎会离真实值越来越远，失去了意义。所以我觉得这个GT位姿完全不能用。你的想法是如何的呢？

**Comment by pengsida** [comment]
你们知道6PACK提供的pose怎么用吗，我发现了几个不同：
1. NOCS的Umeyama算法还会给出一个scales，用于resize 3d bounding box，6PACK似乎没有提供这个参数。https://github.com/hughw19/NOCS_CVPR2019/blob/master/utils.py#L3087
2. NOCS算出的rotation matrix需要transpose，我进行了transpose，发现投影的bounding box更不准了。https://github.com/hughw19/NOCS_CVPR2019/blob/master/utils.py#L3087
3. NOCS会对pose进行from camera world to computer vision frame的变换，https://github.com/hughw19/NOCS_CVPR2019/blob/master/utils.py#L3118

**Comment by pengsida** [comment]
@Liuchongpei nocs提供的testing data的pose是准确的。

**Comment by densechen** [comment]
@Liuchongpei 关于这个GT的误差，其实我之前也有写信问过NOCS的作者，也和6PACK的作者沟通过。包括最近来自新加坡国立大学的一个工作([Shape Prior Deformation for Categorical 6D Object Pose and Size Estimation](https://github.com/mentian/object-deformnet))。大家比较一致的看法是：这个GT的POSE虽然是存在误差的，但是，还是属于可以容忍的。至于你提到很多偏差都超过10度这个问题，其实你仔细去check一下，这类物体可能占的比重不是非常大。如果你觉得真的对你的指标产生了大影响的话，可以自己逐个的手动调整一下。另外，关于数据集的问题，你可以在NOCS的github上面提一个issue，希望作者后期可以release出重新标注的结果（不过应该不会。之前相关的问题都被ignore了。）

**Comment by pengsida** [comment]
Shape prior deformation这篇论文不需要gt RT训练，用nocs coordinate生成的correspondence就可以训练。

**Comment by pengsida** [comment]
@densechen 你们论文里用的RT是用nocs算的吗

**Comment by densechen** [comment]
@pengsida 

> NOCS的Umeyama算法还会给出一个scales，用于resize 3d bounding box，6PACK似乎没有提供这个参数。
Scale并不属于6DoF里面的参数。NOCS的scale是因为nocs map是归一化空间下的表示，所以需要这个scale参数去计算iou。但是6pack是没有这个限制的。

> NOCS算出的rotation matrix需要transpose，我进行了transpose，发现投影的bounding box更不准了
NOCS的pose确实是transpose的。我建议你可以用nocs自己提供的画bbox的代码去测试一下他这个bbox究竟是怎么变换的。另外，建议你可以在生成数据上先画一画。因为生成数据集的pose是极为准确的，如果你用对了，那肯定不会有偏差。

> NOCS会对pose进行from camera world to computer vision frame的变换，
具体的细节我也不记得很清楚了。关于nocs代码的问题，你可以在他的github上提issue去咨询一下他本人。

6PACK的pose好像你可以使用6pack提供的代码计算出结果。而且，6pack的数据好像就是nocs的github上release出来的。

**Comment by pengsida** [comment]
谢谢回复。
对于6PACK的pose，我已经处理好了，只要另外生成scale和对pose做个变换就可以了。
想知道你们用来训练的RT是怎么算的？

**Comment by densechen** [comment]
@pengsida 

> 对于6PACK的pose，我已经处理好了，只要另外生成scale和对pose做个变换就可以了。
想知道你们用来训练的RT是怎么算的？

这个其实也算是NOCS这个数据机的一个不足的地方，就是他没有直接给我们数据集的GT信息，而是release了计算gt的代码。所以我们不得不使用这个代码，重新计算一遍pose。
但是，NOCS这个方法自身是不需要pose做监督的，它只要nocs map就够了。所以这应该也是这个数据集不直接包含pose的原因吧。

**Comment by pengsida** [comment]
是的，这样对后续工作其实挺不公平的，因为他能用gt nocs map训练，而后续工作用的数据难以保证是完全正确的。
你们直接用NOCS的代码生成的object pose吗，有没有试过6PACK的pose会有提升？

**Comment by densechen** [comment]
@pengsida 我的工作是和6PACK的工作，属于同期的工作。所以我们当时还没有6PACK的这项工作。
关于准确性，你可以去可视化出来验证一下就知道了。在生成数据集上，因为它渲染的时候是严格对应的，所以基本上可以当作不存在任何误差。但是，真实的数据集，效果如何大家其实都知道了。

**Comment by pengsida** [comment]
好的，谢谢。
我看6PACK生成的pose在真实数据上会准一些，你之后可以试试。

**Comment by pengsida** [comment]
@densechen 我发现你去年在nocs里提了training data的RT很不准的问题，nocs作者后来有回复你吗，你怎么处理这种很不准的RT的。
https://github.com/hughw19/NOCS_CVPR2019/issues/5#issuecomment-543230930

**Comment by densechen** [comment]
关于这个问题，作者没有给出答复。

**Comment by pengsida** [comment]
谢谢回复。

**Comment by pengsida** [comment]
@densechen 你常用邮箱是densechen@foxmail.com吗，我发了你一个邮件。
