### ISSUE TITLE
Object detection and segmentation

### ISSUE THREAD

**Issue by zyqz97** [densechen/CASS#4]
作者你好！NOCS数据集提供的mask并没有将各个物体区分开，且没有提供目标物体的gt bbox。请问你们是怎么基于NOCS数据集对物体进行分割的？

**Comment by densechen** [comment]
NOCS的数据集是可以计算出MASK的，但是BBOX要自己根据MASK进行计算（好像是这样的）。
你可以看他给的那个评估代码，里面有一段代码是根据NOCS MAP计算GT POSE的。
你可以根据这段代码找出每一个物体对应的NOCSMAP的像素，那个对应的像素，就可以当作是MASK。

**Comment by zyqz97** [comment]
也就是说你们在训练过程中用到的Object detection and cropping是基于NOCSMAP的像素去进行分割的，并没有训练一个分割的网络是吗？

**Comment by densechen** [comment]
嗯嗯，我们没有额外训练一个mask网络。

**Comment by zyqz97** [comment]
好的，十分感谢！
