### ISSUE TITLE
Question about results, Figure 6 (in the paper)

### ISSUE THREAD

**Issue by taeyeopl** [densechen/CASS#5]
Thanks for sharing your work. 
I check that your results use the **json** file. 
Can you share your result of "**.pkl**" types, like NOCS ??? (in the main paper, Figure 6). 
It seems to be of great help when compared to other people with same formats.

**Comment by densechen** [comment]
Thanks for your attention. I am sorry for telling you that we cannot provide `.pkl` for that we forget to save more details about the results, and it has been almost one year ago. 
The result reported in this work [Shape Prior Deformation for Categorical 6D Object Pose and Size Estimation](https://github.com/mentian/object-deformnet) is under the same metric of NOCS. 

I hope this can help you. 
Best

**Comment by taeyeopl** [comment]
Thanks for your reply.
