### ISSUE TITLE
How to implement Batch Mixing?

### ISSUE THREAD

**Issue by Bingo-1996** [densechen/CASS#6]
Dear author, how does the batch mixing mentioned in the experiment be realized? Can you provide the relevant code?
Thanks very much!

**Comment by densechen** [comment]
Sorry for late reply.

Batch Mixing is a simple training trick.
In our experiment process, we find that the synthetic image of NOCS dataset occupied a large portion, but the portion of real image is rather small. So, we use Batch Mixing to keep a better balance between the real and synthetic image. 
There may be many ways to implement Batch Mixing, and we just make sure that at each batch, there always contains real and synthetic image at the same time.

**Comment by Bingo-1996** [comment]
> Sorry for late reply.
> 
> Batch Mixing is a simple training trick.
> In our experiment process, we find that the synthetic image of NOCS dataset occupied a large portion, but the portion of real image is rather small. So, we use Batch Mixing to keep a better balance between the real and synthetic image.
> There may be many ways to implement Batch Mixing, and we just make sure that at each batch, there always contains real and synthetic image at the same time.

Got it!  Thank you for your kind reply!
