### ISSUE TITLE
How to convert "gt_RTs" to "gt_RTs_for_CASS"?

### ISSUE THREAD

**Issue by Liuchongpei** [densechen/CASS#7]
Hello, I found that the evaluation is based on "gt_RTs_for_CASS" in predicted_result/gt/*_.json as the GT pose. Are gt_RTs GT poses from NOCS? Can you help me convert "gt_RTs" to "gt_RTs_for_CASS"?

**Comment by densechen** [comment]
Yes, the GT is calculated with the code provided by `NOCS`. Because we also need some extra information to do the supervised training, so we have to add some extra operation to it. But the GT should be the same with NOCS.

There actually exist some misaligned in the original NOCS GT. And I recommend you could use the GT provided by `6PACK`, the same author of `DenseFusion`. They have rectified same GT bbox manually and also release the final bbox, which I think would be better for you.

Good luck

**Comment by Liuchongpei** [comment]
Thanks for your prompt reply. This is the case. I annotated some pictures collected by myself according to the method provided by NOCS. I want to use CASS to detect my pictures. And I need to convert "gt_RTs" to "gt_RTs_for_CASS" to evaluate the results. Can you help me?

**Comment by densechen** [comment]
Oh. I neither try to use it to detect self annotated images. I am not sure which kind of annotation it is.
If you try to evaluate CASS as a baseline, I think the file under `tools` may be helpful.
If you just want to select an approach to do an application, I think many new approaches may be achieve a better and robust result, such as [Shape Prior Deformation for Categorical 6D Object Pose and Size Estimation](https://github.com/mentian/object-deformnet). 
I hope this would help you.

**Comment by Liuchongpei** [comment]
I want to cite CASS as a baseline. I searched the ‘gt_RTs_for_CASS’ field in the code, but I didn’t find the code to convert ‘gt_RTs’ to ‘gt_RTs_for_CASS’. There should be a piece of code for generating ‘predicted_result/gt/*.json’. Can you provide more information?

**Comment by densechen** [comment]
I am sorry about that I have forgotten that piece of code.
As I remembered, we just use the same code of NOCS to generate the GT first, then we convert it to CASS format.
In CASS, it seems that a transform of the GT is necessary. In addition, we also add the bounding box into GT.

You can refer to https://github.com/densechen/CASS/blob/9ae6dd649c0b74bac4b2fd8f3afd8304a7f37f6b/tools/eval.py#L353 for a reference about the different between CASS GT and NOCE GT.

Best wishes

**Comment by Liuchongpei** [comment]
Thank you very much, I will try it.
